[tox]
minversion = 3.18
envlist = py{37,39}-ansible{29,30}-default
skip_missing_interpreters = true
isolated_build = false

[testenv]
skipsdist = true
skip_install = true
changedir = .
passenv = *
deps =
    ansible29: ansible<3.0
    ansible30: ansible<4.0
    molecule
    molecule-docker
    molecule-podman
    docker
    ansible-lint
commands =
    molecule test -s default
