---
driver:
  name: docker

platforms:
  - name: oraclelinux-8
    image: oraclelinux:8
    pre_build_image: true
  - name: ubuntu-latest
    image: ubuntu:latest
    pre_build_image: true

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../../
  inventory:
    group_vars:
      all:
        vector_version: "0.34.0"
        vector_install_dir: "/opt/vector"

verifier:
  name: ansible

lint: |
  set -e
  ansible-lint

dependency:
  name: galaxy
  options:
    role-file: requirements.yml
